version: "3.9"
services:
  web:
    image: fablanka
    build: .
    ports:
      - "3000:3000"
    extra_hosts:
      - "postgresql:192.168.1.22"
    command: python manage.py runserver 0.0.0.0:3000
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - .:/code  