version: "3.9"
services:
  web:
    image: fablanka
    build: .
    ports:
      - "8000:8000"
    extra_hosts:
      - "postgresql:192.168.1.22"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - IS_DEBUG=True
    volumes:
      - .:/code  